### ISSUE TITLE
Brotli can't find native library if it's been relocated

### ISSUE THREAD

**Issue by NikitaCartes** [BlueMap-Minecraft/BlueMapBrotli#3]
Debian 6.1.0-18-arm64; aarch64; openjdk 21.0.3
Debian 6.1.0-18-amd64; x86_64; openjdk 21.0.3
Windows 10; x86_64; java 21.0.2

Same error:
```
nikita@home-server:~/temp/bluemaop$ java -jar BlueMap-5.2-cli.jar -r
[16:37:43 INFO] Loading BlueMap Addon: bluemap-brotli (config/addons/BlueMapBrotli-1.0-all.jar)
[16:37:44 INFO] Loading resources...
[16:37:45 INFO] Loading textures...
[16:37:46 INFO] Baking resources...
[16:37:46 INFO] Resources loaded.
[16:37:46 INFO] Initializing Storage: 'file_brotli' (Type: 'bluemap:file')
[16:37:46 INFO] Loading map 'overworld_brotli'...
Exception in thread "main" java.lang.UnsatisfiedLinkError: 'java.nio.ByteBuffer de.bluecolored.shadow.brotli4j.encoder.EncoderJNI.nativeCreate(long[])'
        at de.bluecolored.shadow.brotli4j.encoder.EncoderJNI.nativeCreate(Native Method)
        at de.bluecolored.shadow.brotli4j.encoder.EncoderJNI.access$200(EncoderJNI.java:17)
        at de.bluecolored.shadow.brotli4j.encoder.EncoderJNI$Wrapper.<init>(EncoderJNI.java:90)
        at de.bluecolored.shadow.brotli4j.encoder.Encoder.<init>(Encoder.java:48)
        at de.bluecolored.shadow.brotli4j.encoder.BrotliOutputStream.<init>(BrotliOutputStream.java:36)
        at de.bluecolored.shadow.brotli4j.encoder.BrotliOutputStream.<init>(BrotliOutputStream.java:48)
        at de.bluecolored.bluemap.brotli.BlueMapBrotli.lambda$run$0(BlueMapBrotli.java:21)
        at de.bluecolored.bluemap.core.storage.compression.BufferedCompression.compress(BufferedCompression.java:44)
        at de.bluecolored.bluemap.core.storage.file.FileItemStorage.write(FileItemStorage.java:52)
        at de.bluecolored.bluemap.core.map.BmMap.saveTextureGallery(BmMap.java:192)
        at de.bluecolored.bluemap.core.map.BmMap.<init>(BmMap.java:106)
        at de.bluecolored.bluemap.common.BlueMapService.loadMap(BlueMapService.java:247)
        at de.bluecolored.bluemap.common.BlueMapService.getOrLoadMaps(BlueMapService.java:166)
        at de.bluecolored.bluemap.cli.BlueMapCLI.renderMaps(BlueMapCLI.java:93)
        at de.bluecolored.bluemap.cli.BlueMapCLI.main(BlueMapCLI.java:364)
```

It starts working if I build addon with this line commented out:
https://github.com/BlueMap-Minecraft/BlueMapBrotli/blob/1dfd40e4d8eb23ac349f492f311dea6f363a16ad/build.gradle.kts#L30

**Comment by TBlueF** [comment]
I just removed the relocation for now, until someone tells me why it breaks and how to fix :D
(Also: it works on my machine 😅)
